### ISSUE TITLE
代码释放完了记得踢我一下

### ISSUE THREAD

**Issue by StarsTesla** [city-super/MatrixCity#10]
Thanks for your great work！

**Comment by StarsTesla** [comment]
@yixuanli98 Just remind that these files are in sensetime gitlab repo and website, not open for us out of sensetime. And release page shows 404.
<img width="971" alt="image" src="https://github.com/city-super/MatrixCity/assets/45264423/84ec03da-cf07-42ed-afaa-ed8a414469f2">

**Comment by yixuanli98** [comment]
I'm still updating the readme these two days, please be patient.

**Comment by yixuanli98** [comment]
I have released all the documentations.

**Comment by StarsTesla** [comment]
Thanks~
