### ISSUE TITLE
Will you share big_city_depth?

### ISSUE THREAD

**Issue by thucz** [city-super/MatrixCity#12]
Hello! Since depth information is important for 3D reconstruction and NVS, I wonder if you will share big_city_depth?

**Comment by yixuanli98** [comment]
Yes, I will share the depth data.

**Comment by thucz** [comment]
Can you tell me here when you release the depth data of big city?

**Comment by yixuanli98** [comment]
Maybe a week later.

**Comment by thucz** [comment]
Thanks

**Comment by yixuanli98** [comment]
I have already uploaded the depth map of Big City. Just for your reference.

**Comment by thucz** [comment]
Thanks!
