### ISSUE TITLE
Do you have the script to sort the camera poses for video rendering?

### ISSUE THREAD

**Issue by thucz** [city-super/MatrixCity#13]
The given cameras are not sequential(sorted by their locations).  I want to get a more natural sequence. Could you share your scripts when you render the frames in your nerf demo?

**Comment by yixuanli98** [comment]
We use the viewer of [nerfstudio](https://docs.nerf.studio/) to generate the trajectories of our nerf demo. You can refer to this repo.

**Comment by thucz** [comment]
Thanks
