### ISSUE TITLE
Did you use depth map to supervise the geometry of nerf?

### ISSUE THREAD

**Issue by thucz** [city-super/MatrixCity#14]
Hello! I'm very curious about if you only used rgb information in your nerf demo. Or you used both rgb and depth?

**Comment by yixuanli98** [comment]
We only use rgb information in our nerf demo, produced by the [nerfacto](https://docs.nerf.studio/nerfology/methods/nerfacto.html) method of nerfstudio.

**Comment by thucz** [comment]
Thanks!
