### ISSUE TITLE
Retrieve all camera poses in a sequence

### ISSUE THREAD

**Issue by wbteng9526** [city-super/MatrixCity#16]
Hi, thanks for much for your great work. I have a quick question about camera poses. In [https://github.com/city-super/MatrixCity/blob/main/MatrixCityPlugin/docs/Generate-Trajectory.md#5-retrieve-the-camera-pose-you-can-also-modify-the-camera-poses-by-modifying-the-values-in-transform-thereby-changing-the-preview-in-the-viewport-to-achieve-the-desired-picture](url), you mention in step 5 that we are able to retrieve camera pose for each frame. I was wondering if there is a way to export all the camera poses in a sequence at one time. The output format is similar to the transform.json file in your original dataset. Thank you so much for your help.

**Comment by yixuanli98** [comment]
You can refer to [Export-Camere-Poses.md](https://github.com/city-super/MatrixCity/blob/main/MatrixCityPlugin/docs/Export-Camere-Poses.md).
