### ISSUE TITLE
Could you release more codes/models to reproduce the numbers in Table 2 & 3 in the main paper?

### ISSUE THREAD

**Issue by Ganlin-Yang** [city-super/MatrixCity#18]
Hi, thanks for your great work and exceptional effort for producing this dataset!
I'm using MatrixCity dataset for NeRF rendering task. As shown in Table 2 and Table 3 in your paper, you test 5 NeRF methods (NeRF, DVGO, TensoRF, Instant-NGP and MipNeRF) as the benchmark for aerial and street scenes. I have a few questions regarding this:
1) It might be a bit difficult to reproduce the numerical numbers reported in Table 2 and 3, since that the hyperparameters suitable for MatrixCity dataset may be different with the original paper performed on (such as Blender or MipNeRF360). So would you please release the training codes / pretrained models for these five methods as a benchmark to be compared with more easily?
2) Why do you resize the 1080P images into 540 × 960 for training and testing, as mentioned in the supplementary, rather than training and testing on 1080P images directly?

Thanks for your effort and hoping for your replies!

**Comment by yixuanli98** [comment]
1. Which methods you can not reproduce?
2. Yes, we resize the aerial images into 540*960 and street images into 500*500.
