### ISSUE TITLE
Ground-truth intrinsic images

### ISSUE THREAD

**Issue by CCareaga** [city-super/MatrixCity#19]
Hi, great work and thank you for releasing this dataset!

The paper explains that you render out diffuse albedo (and potentially other material parameters) as part of the dataset. I may be missing something, but I wasn't able to find these types of ground truth in the dataset directories, there seems to be only input images and geometry. Do you plan on releasing these additional modalities, or would I need to render the scenes myself?

**Comment by yixuanli98** [comment]
Other materials are large, and it will take a lot of time to upload and download. If your equipment conditions permit, you can render it yourself according to our manual. If not, I can upload our other materials according to your needs.

**Comment by CCareaga** [comment]
If you already have them and it's possible to upload them it would be greatly appreciated. Even just uploading the diffuse albedo component would be really valuable. Re-rendering them would likely take me a much longer than downloading them.

**Comment by yixuanli98** [comment]
Ok, I will first release the diffuse component.

**Comment by yixuanli98** [comment]
Do you need all the data for small city or just a part?

**Comment by CCareaga** [comment]
I'd like to have as much data as possible, so having all of small city would be great.

**Comment by yixuanli98** [comment]
OK, I will release all of small city.

**Comment by yixuanli98** [comment]
Which method do you use to download the data? I can upload it this way first

**Comment by CCareaga** [comment]
Uploading it to huggingface should work for me.

**Comment by yixuanli98** [comment]
I have uploaded the diffuse images of small city to huggingface and baidu wangpan.

**Comment by CCareaga** [comment]
Thank you!
