### ISSUE TITLE
the meaning of down/horizon/outside/vertical in the street folder

### ISSUE THREAD

**Issue by Yang-Xijie** [city-super/MatrixCity#2]
Thanks for your contribution to nerual rendering!

In [the dataset you provide](https://opendatalab.com/bdaibdai/MatrixCity/tree/main):

- /small_city/street/train/small_city_road_down
- /small_city/street/train/small_city_road_horizon
- /small_city/street/train/small_city_road_outside
- /small_city/street/train/small_city_road_vertical

Could you please tell me the meaning of `down`, `horizon`, `outside`, and `vertical` here? It seems that they are four trajectories you chose in the City Sample project, is this correct?

**Comment by Nole21** [comment]
I'm new to this project, have you figured it out?

**Comment by Yang-Xijie** [comment]
I just asked one of the authors. The `small_city` is a block inside the full city. They designed multiple trajectories to capture this block. Generally, two sets are along x and y axes on 2D plane (probably `horizon` and `vertical`), and one set forms a circle outside the block (`outside`). The author forgets what `down` means...

No matter how these trajectories are arranged, you just use all images, or a part of images filtered with poses, in these four folders, as the input to the reconstruction algorithm.

**Comment by jianglh-WHU** [comment]
yeah...that's true

**Comment by Nole21** [comment]
Oh, I see. Thanks!
I have another question, How to find a set of images whose camera is at the same location with different orientation(which forms five cubemaps except the down orientation)? Do there exist some connections between their indices?

**Comment by jianglh-WHU** [comment]
These images share same translations. Their indices may not have any relationships.

**Comment by Nole21** [comment]
Do you mean filter these images with camera extrinsic parameters(same translation)?

**Comment by jianglh-WHU** [comment]
yes
