### ISSUE TITLE
Can we use this plugin to collect binocular camera data？

### ISSUE THREAD

**Issue by niuge12138** [city-super/MatrixCity#20]
Hello! Is it possible to collect binocular camera data with this plugin? The binocular camera consists of two monocular cameras. I want to get the RGB images and depth maps of the left and right cameras. Looking forward to your reply.

**Comment by yixuanli98** [comment]
Yes, you can. Please refer to the last item [https://github.com/city-super/MatrixCity/blob/main/MatrixCityPlugin/docs/Generate-Trajectory.md#note](https://github.com/city-super/MatrixCity/blob/main/MatrixCityPlugin/docs/Generate-Trajectory.md#note) to write your own trajectory function.
