### ISSUE TITLE
axis and directions of transformations?

### ISSUE THREAD

**Issue by AIBluefisher** [city-super/MatrixCity#21]
Hi,

May I know the axis (e.g. down-right-backwards) and the direction (from camera to world or world to camera) of the camera poses?

**Comment by yixuanli98** [comment]
The camera poses are camera to world. We use the same pose coordinate system as original [NeRF repo](https://github.com/bmild/nerf): the local camera coordinate system of an image is defined in a way that the X axis points to the right, the Y axis upwards, and the Z axis backwards as seen from the image.

**Comment by AIBluefisher** [comment]
Thanks for your explanation. It would be better to make it clear on README.

**Comment by AIBluefisher** [comment]
I also have a question: for the aerial_street_fusion dataset, the camera poses in the aerial images seem not to share the same coordinate frame with the camera poses in the street images:
![aerial_steet_fusion](https://github.com/city-super/MatrixCity/assets/18096136/909e25ef-8702-4d21-808e-10c4a1811618)

**Comment by yixuanli98** [comment]
> Thanks for your explanation. It would be better to make it clear on README.

We write the coordinate system here https://github.com/city-super/MatrixCity?tab=readme-ov-file#data-download.

**Comment by yixuanli98** [comment]
> I also have a question: for the aerial_street_fusion dataset, the camera poses in the aerial images seem not to share the same coordinate frame with the camera poses in the street images: ![aerial_steet_fusion](https://private-user-images.githubusercontent.com/18096136/300169781-909e25ef-8702-4d21-808e-10c4a1811618.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYzNTE4MTcsIm5iZiI6MTcwNjM1MTUxNywicGF0aCI6Ii8xODA5NjEzNi8zMDAxNjk3ODEtOTA5ZTI1ZWYtODcwMi00ZDIxLTgwOGUtMTBjNGExODExNjE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI3VDEwMzE1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwNDU1ODdhNmY5YmQzMGZmYWM3ODRjYTNmNmYzOGZmZmQ1YTQ5MTFkOGQzZWRiMDliNzdhMDg5Mzk4ZGM5NmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CJh8zqmJ8beqxq83sMQF_4TcYWVP3X9cwUdxi1Mx2vg) I visualize the camera poses using COLMAP's GUI. As we can observe, the camera poses of the street images are higher than the aerial images. There must be a transformation to align the camera poses together. Or am I missing something?

They are in the same coordinate system. Our coordinate system is not colmap system. So I think it is not reasonable to use the colmap GUI to visualize the camera poses. You can see the transforms_train.json. The height of street is 0.03 and the height of aerial is 2. The unit is 100m. You can read the explanation of our data structure https://github.com/city-super/MatrixCity?tab=readme-ov-file#data-structure.

**Comment by yixuanli98** [comment]
> > Thanks for your explanation. It would be better to make it clear on README.
> 
> We write the coordinate system here https://github.com/city-super/MatrixCity?tab=readme-ov-file#data-download.

Thanks for you suggestion. We will open a new section to explain this thing to make it easier to notice

**Comment by yixuanli98** [comment]
> > > Thanks for your explanation. It would be better to make it clear on README.
> > 
> > 
> > We write the coordinate system here https://github.com/city-super/MatrixCity?tab=readme-ov-file#data-download.
> 
> Thanks for you suggestion. We will open a new section to explain this thing to make it easier to notice

We have updated the information here https://github.com/city-super/MatrixCity?tab=readme-ov-file#pose-file-structure.

**Comment by AIBluefisher** [comment]
> > > > Thanks for your explanation. It would be better to make it clear on README.
> > > 
> > > 
> > > We write the coordinate system here https://github.com/city-super/MatrixCity?tab=readme-ov-file#data-download.
> > 
> > 
> > Thanks for you suggestion. We will open a new section to explain this thing to make it easier to notice
> 
> We have updated the information here https://github.com/city-super/MatrixCity?tab=readme-ov-file#pose-file-structure.

Thanks for your help and the quick update!

**Comment by AIBluefisher** [comment]
> > I also have a question: for the aerial_street_fusion dataset, the camera poses in the aerial images seem not to share the same coordinate frame with the camera poses in the street images: ![aerial_steet_fusion](https://private-user-images.githubusercontent.com/18096136/300169781-909e25ef-8702-4d21-808e-10c4a1811618.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYzNTE4MTcsIm5iZiI6MTcwNjM1MTUxNywicGF0aCI6Ii8xODA5NjEzNi8zMDAxNjk3ODEtOTA5ZTI1ZWYtODcwMi00ZDIxLTgwOGUtMTBjNGExODExNjE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI3VDEwMzE1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwNDU1ODdhNmY5YmQzMGZmYWM3ODRjYTNmNmYzOGZmZmQ1YTQ5MTFkOGQzZWRiMDliNzdhMDg5Mzk4ZGM5NmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CJh8zqmJ8beqxq83sMQF_4TcYWVP3X9cwUdxi1Mx2vg) I visualize the camera poses using COLMAP's GUI. As we can observe, the camera poses of the street images are higher than the aerial images. There must be a transformation to align the camera poses together. Or am I missing something?
> 
> They are in the same coordinate system. Our coordinate system is not colmap system. So I think it is not reasonable to use the colmap GUI to visualize the camera poses. You can see the transforms_train.json. The height of street is 0.03 and the height of aerial is 2. The unit is 100m. You can read the explanation of our data structure https://github.com/city-super/MatrixCity?tab=readme-ov-file#data-structure.

I converted the poses to COLMAP's format. There should be some other issues with my conversion code. I will try to fix it later.
