### ISSUE TITLE
Is there any invalid mask for ground-truth depth and surface normal?

### ISSUE THREAD

**Issue by guangkaixu** [city-super/MatrixCity#22]
Hi, thanks for your great work and dataset! I would like to use it as an awesome training and testing dataset, but I have some questions about it:

1. Is there any invalid mask for GT depth and surface normal? I visualize the depth map and find that the depth value of the sky is not 655.35m, and it is much closer than the farest depth value in the depth image, which may mislead the training process.
2. The same problem exists in the surface normal. Theoretically, the surface normal of the sky area is invalid, but I cannot distinguish them during training.

Hoping for your reply~

**Comment by yixuanli98** [comment]
1. Why the depth value of sky should be 655.35m?
2. The normal vectors of the sky area are (0, 0, 0) as visualized in our teaser, which are directly read from the exr file without normalization. Other part are not (0, 0, 0). You can distinguish the sky area based on this.

**Comment by guangkaixu** [comment]
Thanks! I checked the depth value of the sky region, it is the maximum value of an uint16 image. The 655.35m just represents the maximum depth value for unit16 with a depth scale of 100.
