### ISSUE TITLE
Questions about SceneDepth to "metric depth(distance from camera center to scene)"

### ISSUE THREAD

**Issue by Gear-dev-sudo** [city-super/MatrixCity#24]
Hi, ya'all. This might be a stupid question, is the depth data rendered in the pipeline relative depth data? are there any way for me to use this as metric depth?

**Comment by jianglh-WHU** [comment]
Hi! The depth data rendered in UE is metric depth with centimeters.

**Comment by Gear-dev-sudo** [comment]
In my setup, I put a unit cube right below my camera, with the camera facing down towards the block's top surface. But in the depth image I got, the depth value of the whole top surface of the block is the same, which is not supposed to be right, (since the depth value should be the distance of thar pixel to the center of the camera in the 3d simulation), and I'm having 20-30 cm of errors across all vertices of the unit cube. My camera is right above the center of the unit cube 6 meters.

**Comment by jianglh-WHU** [comment]
Could you give me some results? Or maybe you can refer this issue [https://github.com/city-super/MatrixCity/issues/4](https://github.com/city-super/MatrixCity/issues/4)

**Comment by Gear-dev-sudo** [comment]
![image](https://github.com/city-super/MatrixCity/assets/85670459/75dde21f-8792-4819-9f5b-8f7c734534c7)
My setup is this, the camera to the unit block is 300 cm, but the depth readout exr image of this is that the unit block in the middle's top surface readout
![Screenshot 2024-04-01 221148](https://github.com/city-super/MatrixCity/assets/85670459/d94d8433-99ff-47a7-a81b-c158c984f88a)
are all 300 cm, which is not correct. So, Basically, I just wonder that is the SceneDepth in UE5 and in you guys's work are accurate enough

**Comment by yixuanli98** [comment]
Depth in UE is the distance to the camera plane, not the camera.

**Comment by Gear-dev-sudo** [comment]
> Depth in UE is the distance to the camera plane, not the camera, which can transform into each other

Is it the camera frustum? like the distance is calculated from the near clipping plane of the camera frustum to the pixel being rendered?

**Comment by yixuanli98** [comment]
The depth in UE is "z-depth", which refers to the distance between a point in the 3D space and the camera along the Z-axis, which is typically aligned with the camera's direction of view. This distance helps in determining which objects are in front of others and thus should be rendered on top when creating a 2D image from a 3D scene – a concept known as depth buffering.

**Comment by Gear-dev-sudo** [comment]
Ok, may I ask, is there a way to covert this into distance from camera center to the objects in the scene? I'm essentially trying to do this for a metric depth estimation DL task.

**Comment by Gear-dev-sudo** [comment]
> The depth in UE is "z-depth", which refers to the distance between a point in the 3D space and the camera along the Z-axis, which is typically aligned with the camera's direction of view. This distance helps in determining which objects are in front of others and thus should be rendered on top when creating a 2D image from a 3D scene – a concept known as depth buffering.

Thank you for clarifying this.

**Comment by yixuanli98** [comment]
> Ok, may I ask, is there a way to covert this into distance from camera center to the objects in the scene? I'm essentially trying to do this for a metric depth estimation DL task.

Hope this picture can help you understand. In addition, because our exr is float16, the maximum range is 65504 centimeters. So when using depth, please note that all parts equal to 65504 are invalid. Later, we will update the script loading depth and normal to determine the invalid parts and a wider range of depth maps. 

![z-depth_transfer](https://github.com/city-super/MatrixCity/assets/25405927/ca6de05e-1e53-43fa-b2f7-b6a884f68a38)

**Comment by Gear-dev-sudo** [comment]
Thank you for that! This explains a lot, however, is there a way to really get the "distance from camera"?
