### ISSUE TITLE
Issues when rendering data

### ISSUE THREAD

**Issue by zhicongsun** [city-super/MatrixCity#26]
Dear Dr. Li, 

I encountered the following problem while rendering data. Have you encountered the same problem before and do you have any solutions. Thank you for your answer.
<img width="874" alt="image" src="https://github.com/city-super/MatrixCity/assets/36354445/14babd6c-238e-4005-adc4-b81366a5be9b">

**Comment by yixuanli98** [comment]
This information is normal if you have successfully rendered the images.
