### ISSUE TITLE
Issues when Generating Custom Trajectory

### ISSUE THREAD

**Issue by zhicongsun** [city-super/MatrixCity#28]
Dear Dr. Li,

I encountered the following problem while Generating Custom Trajectory using the command 'python misc/run_cmd_async.py'. This issue seems to be caused by the package ‘pydantic’ being too up-to-date. However, the problem still persists even after I tried using the 1.x version of the pydantic. Have you encountered the same problem before and do you have any solutions. Thank you for your answer.

![image](https://github.com/city-super/MatrixCity/assets/36354445/2186e7a8-5763-41c4-9272-64599948f48a)

**Comment by niuge12138** [comment]
Hello, I have encountered the same problem. I changed "pydantic" in "MatrixCityPlugin/misc/requirements_ue.txt" to "pydantic==1.10.8" and executed `pip install -r misc/requirements_ue.txt` again. It works.

**Comment by yixuanli98** [comment]
> Hello, I have encountered the same problem. I changed "pydantic" in "MatrixCityPlugin/misc/requirements_ue.txt" to "pydantic==1.10.8" and executed `pip install -r misc/requirements_ue.txt` again. It works.

Thank you for your information!

**Comment by zhicongsun** [comment]
> Hello, I have encountered the same problem. I changed "pydantic" in "MatrixCityPlugin/misc/requirements_ue.txt" to "pydantic==1.10.8" and executed `pip install -r misc/requirements_ue.txt` again. It works.

This works! Thank you for your information!
