### ISSUE TITLE
About MatrixCity/aerial_street_fusion

### ISSUE THREAD

**Issue by zachzhang07** [city-super/MatrixCity#30]
Hi, thanks for your excellent work!
I noticed that there is a folder named 'aerial_street_fusion' in MatrixCity. I'm wondering which block is included in this folder, or which pcd file can bu used to initial 'aerial_street_fusion' area in 3DGS.

**Comment by jianglh-WHU** [comment]
Hi~In our paper, we conducted an experiment that involved fusing data from both aerial and street views. The folder named `aerial_street_fusion` represents this data. For the pcd file format, we have provided all the ply files in the `small_city_pointcloud` folder. Specifically, the Block_small.ply file in the merge folder corresponds to the point cloud of the aerial_street_fusion data.

**Comment by zachzhang07** [comment]
Thanks!

**Comment by BitCalSaul** [comment]
@jianglh-WHU Hi, thanks so much for sharing the dataset!

I couldn’t find Block_small.ply in the small_city_pointcloud folder. There are only two zip files: matrixcity_point_cloud_ds.zip and matrixcity_point_cloud_ds20.zip. I assume you’re referring to the second one?

Also, I downloaded aerial.tar and street.tar from the MatrixCity/aerial_street_fusion folder. After decompression, I noticed that only the street dataset includes a train/test split, while the aerial dataset does not. May I ask if there’s a specific reason for this?

Thank you very much!

**Comment by jianglh-WHU** [comment]
1. Sorry @BitCalSaul, for the first question, I forgot it. You can use this ply and you can also generate ply by yourself.
2. You can refer to transforms_test.json for the test split.

[Block_small.ply.zip](https://github.com/user-attachments/files/20989674/Block_small.ply.zip)

**Comment by BitCalSaul** [comment]
@jianglh-WHU thank you very much for your quick reply!

May I ask about the intended purpose of the two files: matrixcity_point_cloud_ds.zip and matrixcity_point_cloud_ds20.zip?

If I want to train on all blocks from both MatrixCity/small_city/aerial and MatrixCity/small_city/street, should I use these zip files?

Also, just to confirm:
	•	If I want to train high-resolution renderings, I should use matrixcity_point_cloud_ds.zip;
	•	If I want to train low-resolution renderings, I should use matrixcity_point_cloud_ds20.zip.

Is that understanding correct?
I truly appreciate your support!

**Comment by jianglh-WHU** [comment]
Here, matrixcity_point_cloud_ds is the original ply for the block_all scene, and we downsample 20 times to avoid OOM while training 3DGS, that is matrixcity_point_cloud_ds20.

**Comment by BitCalSaul** [comment]
@jianglh-WHU Thank you for your clarification!

**Comment by BitCalSaul** [comment]
Hi @jianglh-WHU ,

We were discussing how the quality of the initial .ply point cloud might affect the final PSNR when training 3D Gaussian Splatting ([Link for your information](https://github.com/nyu-systems/Grendel-GS/issues/49#issuecomment-3021543222)).

Since MatrixCity provides some precomputed .ply files, we’re curious about how these were generated — were they created from ground-truth RGBD depth, or via COLMAP/SfM?

Thanks for clarifying!

**Comment by jianglh-WHU** [comment]
Please refer to https://github.com/city-super/MatrixCity?tab=readme-ov-file#export-point-clouds. The ply we provided is from gt RGBD depth.

**Comment by BitCalSaul** [comment]
@jianglh-WHU Hi, thanks again for your great work and for sharing MatrixCity!

I have a quick clarification about the street-view training data.
I combined the following four subfolders:

```
MatrixCity/small_city/street/train/small_city_road_down

MatrixCity/small_city/street/train/small_city_road_horizon

MatrixCity/small_city/street/train/small_city_road_outside

MatrixCity/small_city/street/train/small_city_road_vertical
```

Together, these seem to cover the full "road" training set.

For training with 3DGS using a .ply point cloud, I noticed there are three candidate files:

```
MatrixCity/small_city_pointcloud/point_cloud/street/Block_A.ply (132M points)

MatrixCity/small_city_pointcloud/point_cloud/street/Block_all.ply (1085M points)

MatrixCity/small_city_pointcloud/point_cloud/street/Block_small.ply (11M points)
```

May I ask which one you would recommend for training with the road dataset?
I am a bit confused about the naming convention and their intended usage.

Thanks a lot for your time and clarification!
