### ISSUE TITLE
关于smallcity 各个block数据划分的疑问？

### ISSUE THREAD

**Issue by smart4654154** [city-super/MatrixCity#31]
在论文中介绍了smallcity 各个block数据划分的范围。
![image](https://github.com/city-super/MatrixCity/assets/152783898/1735d838-ce75-4678-b56b-a9ba185b085b)

但是，我解压block4分区发现，block4图片里有海洋部分（比如block4/159），但根据你们的分割方式，block4应该全是陆地，请问是为什么？十分感谢。
![image](https://github.com/city-super/MatrixCity/assets/152783898/49535f04-6aad-498a-9667-209ee1217cfd)

**Comment by yixuanli98** [comment]
Because the box of block 4 is the range of the camera in x-y plane, but the camera is very high and contains perspectives looking outside the block, so you will see the sea.
