### ISSUE TITLE
增加照片后训练效果变差

### ISSUE THREAD

**Issue by smart4654154** [city-super/MatrixCity#32]
这是我用3DGS算法训练block5的结果（block_5 的数量为: 231），靠海的部分很清晰
![image](https://github.com/city-super/MatrixCity/assets/152783898/265f9812-7f56-4f1e-bb50-1bc40d76ca00)
但是当我使用相同的算法，使用block5及其周围的一些数据（block_3 的数量为: 49，block_4 的数量为: 24，block_5 的数量为: 231，block_6 的数量为: 48），训练结果很模糊，很多飘浮的高斯点
![image](https://github.com/city-super/MatrixCity/assets/152783898/04d17ba6-8f5f-49b0-bb4a-c7cb85c880cd)

请问这跟你们提供的数据有关系吗？
似乎跟json文件里C2W矩阵有关？请问small_city\aerial\pose\block_all\transform_train.json文件各个block的transform_matrix是在相同的世界坐标系吗？
或者是其他原因？
十分感谢

**Comment by jianglh-WHU** [comment]
what's your init points?

**Comment by smart4654154** [comment]
> what's your init points?

十分感谢你的回复，我使用的是随机点云训练block5  或者   block5及其周围的一些数据。
我正在探索原因，由于数据量大，我对照片进行了2倍下采样，但是transforms_train.json文件没有修改，我是一个初学者，你可以告诉我json文件如何对应修改吗，教程/其他资源都可以？十分感谢

**Comment by jianglh-WHU** [comment]
If you downsample the images by a factor of 2, you must also downsample the intrinsic parameters by the same factor while keeping the extrinsic parameters unchanged. Furthermore, if you choose to initialize using random points, it is necessary to ensure that they belong to the corresponding region. By the way, we have provided the point cloud for initializing the GS.
