### ISSUE TITLE
对Figure2（a）的困惑

### ISSUE THREAD

**Issue by smart4654154** [city-super/MatrixCity#33]
十分感谢你们的工作，感谢你们的数据。
根据 Figure2（a）block5只有几个楼，但实际训练却有很多楼（图2红圈），我猜测你们的 Figure2（a）进行了简化，我需要检查训练结果是否与真实一致，可以麻烦你们制作一份数据的俯视图吗（无需场景简化）？
十分感谢
![image](https://github.com/city-super/MatrixCity/assets/152783898/c2a82114-d65a-4d24-a4eb-7bb15787fd69)

![image](https://github.com/city-super/MatrixCity/assets/152783898/f6457b2f-dc8c-4cf1-a65d-6ad6e49b7803)

**Comment by jianglh-WHU** [comment]
Figure2(a) is the bev top view, please note that our aerial data is 45 degree tilted photography, so such a result is normal.
