### ISSUE TITLE
The coordinate system of normal 

### ISSUE THREAD

**Issue by HarshWinterBytes** [city-super/MatrixCity#34]
Hi, thank you for making such a amazing dataset!
I wonder if your normals are all defined under the world coordinate system. This doubt if from that when I visualizing the normal I noticed that the normal color of the left and right side of the camera is similar in different scenes as shown in following images:

![image](https://github.com/user-attachments/assets/ae122777-4120-4ea8-8c4b-0a2ba662ec6d) ![image](https://github.com/user-attachments/assets/da814768-0167-4b88-a6d7-18ff513072eb)

The code for visualizing the normal: `color_normal = (normal + 1) * 127.5`

If the normals are defined under the world coordinate system, I wonder how to turn it form world coordinate system to camera system correctly.

Waiting for your early reply! 
Best wishes!

**Comment by yixuanli98** [comment]
Yes, our normals are all defined under the world coordinate system. We have provided the c2w matrix for each camera in the pose file. You can get the w2c matrix by taking the inverse of c2w to translate the normals from world coordinate system to camera system.
