### ISSUE TITLE
 Inquiry about aerial_street_fusion

### ISSUE THREAD

**Issue by oungji212** [city-super/MatrixCity#35]
Thank you very much for your valuable work!

According to the discussion in [issue #30](https://github.com/city-super/MatrixCity/issues/30), the ply file for 'aerial_street_fusion' is indicated to be 'Block_small.ply' in the 'small_city_pointcloud/merge' directory. 
I am attempting to train 3DGS and Octree-GS using the pose(json) and images from  'aerial_street_fusion', alongside 'Block_small.ply'.

However, when rendering using the 'readCamerasFromTransforms' function from Octree-GS ([link to function](https://github.com/city-super/Octree-GS/blob/main/scene/dataset_readers.py#L204)), the rendered images appear empty, with nothing being displayed.

Could you please provide some code or guidance on how to properly initialize 3DGS/Octree-GS with the provided ply file, while using the 'transforms.json' from 'aerial_street_fusion' for training?

Thank you!

**Comment by jianglh-WHU** [comment]
Well, there's nothing different between matrixcity and other datasets. Load ply using [#L120](https://github.com/city-super/Octree-GS/blob/703b7ba6e0d12ddf0a31f931377a6ef67c82f2a4/scene/dataset_readers.py#L120) and load json using [#L204](https://github.com/city-super/Octree-GS/blob/703b7ba6e0d12ddf0a31f931377a6ef67c82f2a4/scene/dataset_readers.py#L204).
If you have more questions, please feel free to let me know and show some visualized results.

**Comment by oungji212** [comment]
After several attempts, I found that changing the existing code:

```python
c2w = np.array(frame["transform_matrix"])
c2w[:3, 1:3] *= -1
```

to the following:

```python
c2w = np.array(frame["transform_matrix"])
c2w[:3, :] /= 100
c2w[:3, 1:3] *= -1
```

resolved the issue. Thank you for your reply!
