### ISSUE TITLE
 Clarification on Weather Variation Capabilities and Recommendations for Complex Weather Datasets

### ISSUE THREAD

**Issue by ChaoyiZh** [city-super/MatrixCity#36]
Hi,

Thank you for your excellent work on this project. I have been exploring the capabilities described in your paper, particularly regarding weather variations. I understand that the system can handle changes in lighting and fog conditions, but I have a few questions:

Is it possible to extend the weather variation capabilities to more complex scenarios such as extreme weather conditions (e.g., heavy rain, snow)?
If these capabilities are not currently supported, are there any plans to include such features in the future?
Can you recommend any similar datasets that focus on varying weather conditions, including extreme weather scenarios?
Your insights would be greatly appreciated. Thank you for your time and assistance.

**Comment by yixuanli98** [comment]
Currently, the City Sample does not support complex weather. You can go to the UE marketplace to find scenes that support complex weather.
