### ISSUE TITLE
关于big city的street部分的pose文件生成问题

### ISSUE THREAD

**Issue by HarshWinterBytes** [city-super/MatrixCity#38]
您好！
我尝试用[generate_split.py](https://github.com/city-super/MatrixCity/blob/main/scripts/generate_split.py)生成big city的street部分的transform_pose.json文件。我注意到你们用max_x，min_x，max_y，min_y来过滤，我在使用时使用的是默认值，并统计了一下过滤前后的数据量（bottom、left、right、top四个区域一起），如下：
过滤前：train: 258015 frames, test: 28430 frames
过滤后：train: 6745 frames, test: 740 frames

由于过滤前后的数据量差异太大了，我想问一下是否是正常的，或者说对于big city的street部分不能使用默认的max_x，min_x，max_y，min_y？

会产生这个疑问的另一个原因是，我统计了一下你们提供的small city中street部分的pose文件中的max_x，min_x，max_y，min_y，发现值分别为：
```
max_x = -1.2021224975585938
min_x = -8.515166015625
max_y = 2.1065020751953125
min_y = -5.469083251953125
```
和[generate_split.py](https://github.com/city-super/MatrixCity/blob/main/scripts/generate_split.py)中的默认值有较大差异

期待您的回复。
祝好！

**Comment by yixuanli98** [comment]
The default value is for the block A of street in small city, which is much smaller than bit city. You can define your own range.

**Comment by HarshWinterBytes** [comment]
> The default value is for the block A of street in small city, which is much smaller than bit city. You can define your own range.
感谢您的回复！

请问有可以参考的值吗？我看数据中有很多无效的图片（只有地面或者相机朝向海面的），我要如何设置一个合理的范围来获得尽可能多的合理有效的数据呢？
