### ISSUE TITLE
obj 

### ISSUE THREAD

**Issue by wtj-zhong** [city-super/MatrixCity#5]
Thank you for your work. 
I would like to know if your synthetic data has a corresponding grid model, similar to obj format.

**Comment by yixuanli98** [comment]
We have released the depth and normal maps. Maybe you can try to get the mesh from the multi-view depth and normal maps. Because the city sample is a huge project and it is impossible to get the whole map mesh from UE.

**Comment by wtj-zhong** [comment]
Hello, I would like to ask if you have the orthophoto generated by the model.

**Comment by yixuanli98** [comment]
Currently, we do not provide the orthophoto.

**Comment by yixuanli98** [comment]
UE has the orthographic camera, but we have not verified its accuracy. Maybe there exists some bug like panorama camera.
