### ISSUE TITLE
Transforms for small_city

### ISSUE THREAD

**Issue by Snosixtyboo** [city-super/MatrixCity#9]
Hi, thanks so much for providing this great dataset!

Would it be possible to provide the transforms.json for the entire small city as download along with the images? This would be super helpful to us.

Best,
Bernhard

**Comment by yixuanli98** [comment]
We have released all the json files for small city. What do you means the transforms.json for the entire small city?

**Comment by Snosixtyboo** [comment]
Thanks for the reply! Going through the huggingface data, i can find transforms for block_a and block_small of small city. But they only seem to contain a fraction of the shots in small city (the biggest, block_a has ~6000 images). It's possible I don't understand the structure well?

**Comment by Snosixtyboo** [comment]
You are correct! Sorry, i confused myself with the directory structure. Thanks a lot!

**Comment by yixuanli98** [comment]
Please note that the files in the "pose" folder represent the splits of our dataset, with coordinate units in hectometers. Each file is associated with a "transforms.json" file, which contains the original pose exported from Unreal Engine. The rotation matrices in these JSON files should be multiplied by 100 for normalization, and the position units are in meters.
